set my api and created add blog, get a single blog, get all blogs end…
jimmymut/my-brand-backend pull request #1
Opened 2022-12-20 16:31 UTC by jimmymut

… points

made all routes endpoints, refactored my codes to routes-controller-modle, validated some endpoints with joi and refactored to es6

added authentication on some routes

2022-12-20 16:47 UTC, jimmymut commented
I am going to work on the comments you just said on

2022-12-21 07:27 UTC, Eli250 requested changes
Work on all comments.

2022-12-21 07:27 UTC, Eli250 commented on src/authentications/auth.js
> +// opts.issuer = 'accounts.examplesoft.com';
Remove these comments

2022-12-21 07:27 UTC, Eli250 commented on src/middlewares/signInAuth.js
> +// import passport from "passport";
Delete all unused files.

2022-12-21 07:28 UTC, merged